# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YjhOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('order_info', models.CharField(blank=True, max_length=400, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('waiter_id', models.IntegerField(blank=True, null=True)),
                ('deal_id', models.IntegerField(blank=True, null=True)),
                ('deal_count', models.IntegerField(blank=True, null=True)),
                ('address_id', models.IntegerField(blank=True, null=True)),
                ('coupon_id', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('price_none', models.FloatField(blank=True, null=True)),
                ('price_all', models.FloatField(blank=True, null=True)),
                ('level_offer', models.IntegerField(blank=True, null=True)),
                ('pay_ment', models.CharField(blank=True, max_length=20, null=True)),
                ('pay_buyer', models.CharField(blank=True, max_length=20, null=True)),
                ('food_id', models.IntegerField(blank=True, null=True)),
                ('food_details', models.TextField(blank=True, null=True)),
                ('food_deliverytime', models.CharField(blank=True, max_length=20, null=True)),
                ('food_remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('food_tip', models.CharField(blank=True, max_length=10, null=True)),
                ('food_supplier', models.TextField(blank=True, null=True)),
                ('food_typeid', models.IntegerField(blank=True, null=True)),
                ('food_countsupplier', models.IntegerField(blank=True, null=True)),
                ('food_countgrab', models.IntegerField(blank=True, null=True)),
                ('food_info', models.TextField(blank=True, null=True)),
                ('food_checktime', models.CharField(blank=True, max_length=255, null=True)),
                ('order_type', models.IntegerField(blank=True, null=True)),
                ('food_order_type', models.IntegerField(blank=True, null=True)),
                ('refund_time', models.CharField(blank=True, max_length=11, null=True)),
                ('refund_type', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('assess_id', models.IntegerField(blank=True, null=True)),
                ('waiter_time', models.CharField(blank=True, max_length=11, null=True)),
                ('waiter_sorce', models.IntegerField(blank=True, null=True)),
                ('waiter_isprice', models.IntegerField(blank=True, null=True)),
                ('waiter_assess', models.CharField(blank=True, max_length=300, null=True)),
                ('drive_id', models.IntegerField(blank=True, null=True)),
                ('drive_sorce', models.IntegerField(blank=True, null=True)),
                ('drive_info', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_neck', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_neck', models.CharField(blank=True, max_length=255, null=True)),
                ('is_notice', models.IntegerField(blank=True, null=True)),
                ('is_remove', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=11, null=True)),
                ('food_time', models.TextField(blank=True, null=True)),
                ('food_status', models.TextField(blank=True, null=True)),
                ('pay_type', models.IntegerField(blank=True, null=True)),
                ('card_virtual', models.CharField(blank=True, max_length=40, null=True)),
                ('time_usestart', models.CharField(blank=True, max_length=11, null=True)),
                ('is_userd', models.IntegerField(blank=True, null=True)),
                ('qrcode', models.CharField(blank=True, max_length=32, null=True)),
                ('from_adv', models.IntegerField(blank=True, null=True)),
                ('from_advid', models.IntegerField(blank=True, null=True)),
                ('from_other', models.CharField(blank=True, max_length=255, null=True)),
                ('is_error', models.IntegerField(blank=True, null=True)),
                ('error_pay', models.TextField(blank=True, null=True)),
                ('xml', models.TextField(blank=True, null=True)),
                ('dbarray', models.TextField(blank=True, null=True)),
                ('backinfo', models.TextField(blank=True, null=True)),
                ('pay_time', models.CharField(blank=True, max_length=11, null=True)),
                ('supplier_remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('delivery_type', models.IntegerField(blank=True, null=True)),
                ('delivery_id', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_price', models.FloatField(blank=True, null=True)),
                ('delivery_page', models.FloatField(blank=True, null=True)),
                ('score_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yjh_order',
                'managed': False,
            },
        ),
    ]
