# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-28 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgination', '0004_auto_20180127_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m/%d', verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.CharField(max_length=50, verbose_name='\u6559\u5b66\u7279\u2020\u70b9'),
        ),
    ]
