# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-28 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgination', '0005_auto_20180128_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.CharField(max_length=50, verbose_name='\u6559\u5b66\u7279\u70b9'),
        ),
    ]
